- name: Validate & Homologate GitOps repos (PROD -> DRP)
  hosts: invd-ts-ansible
  gather_facts: true
  become: true
  vars_files:
    - ./roles/validate_gitops_repos/vars.yml

  roles:
    - role: validate_gitops_repos
